// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $game_id_ from "./routes/game/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $lobby_id_ from "./routes/lobby/[id].tsx";
import * as $login from "./routes/login.tsx";
import * as $Board from "./islands/Board.tsx";
import * as $Button from "./islands/Button.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $lobby_Lobbies from "./islands/lobby/Lobbies.tsx";
import * as $lobby_LobbyCard from "./islands/lobby/LobbyCard.tsx";
import * as $lobby_LobbyPage from "./islands/lobby/LobbyPage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/game/[id].tsx": $game_id_,
    "./routes/index.tsx": $index,
    "./routes/lobby/[id].tsx": $lobby_id_,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/Board.tsx": $Board,
    "./islands/Button.tsx": $Button,
    "./islands/Login.tsx": $Login,
    "./islands/lobby/Lobbies.tsx": $lobby_Lobbies,
    "./islands/lobby/LobbyCard.tsx": $lobby_LobbyCard,
    "./islands/lobby/LobbyPage.tsx": $lobby_LobbyPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
